#  Python for Economic and Social Data Science

## 17th July, 2024
---
## Homework Three

### Question One: While loops
    
Write a spaceship launch style countdown timer using ```while```. The program should:

1. Take a number as input from the user (i.e. the number of seconds for the countdown).
2. Check that the user input is a number.
3. Countdown to zero
4. Blastoff!

In [2]:
# Answer One here
import time
def counter_timer():
    try:
        seconds = int(input('enter the number of the condition:'))
        
        if seconds < 0:
            print('please enter a positive seconds')
            return
        while seconds > 0:
            print(seconds)
            seconds -= 1
            time.sleep(1)
            
        print('Blasr off!!!')
    except ValueError:
        print('Invalid input,please enter another number!')
        
counter_timer()
            

enter the number of the condition:9
9
8
7
6
5
4
3
2
1
Blasr off!!!


### Question Two: Psuedocode

Write the following as pseudocode (i.e. go in reverse: from real code to pseudocode):
    
```python
def square_numbers(maxnumber):
    square_numbers_list = []
   
    for i in range(0,maxnumber):
        if int(i**.5) == i**.5:
            square_numbers_list.append(i)
    
    return square_numbers_list

print("This program will print all square numbers from 0 to your maximum number.")
a = input("Please enter a maximum number: ")

square_numbers_list = []

try:
    if int(a):
        print(square_numbers(int(a)))

except ValueError:
    print("You did not enter a valid integer.")
```

In [2]:
# Answer Two here
FUNC square_numbers(maxnumber)
    INTINALIZE square_numberlist_list AS an empty list
    
    FOR i FROM 0 TO maxnumber - 1
        IF the squre root of i is an integer
            APPEND I to square_number_list
            
    RETURN square_numbers_list
    
PRINT "This program will print all square numbers from 0 to your maximum number."
SET a as input("Please enter a maximum number: ")

INITIALIZE square_numbers_lsit AS an empty list

TRY 
    IF a can be converted to an integer
     PRINT result
EXCEPT ValuedError
    PRINT "You did not enter a valid integer"

## Question Three. Building a function

Build a function which accepts a string as input. Use the functions to count the number of unique **letters** below, and print out the function return (length). 

```python
phrase_one = "Well here we are"

phrase_two = "Back in sunny Xi'an!"
```

To be more advanced: how many capital letters are there?

In [18]:
# Answer Three here
#import string
#def uniqueletter(line):
#    puntable=str.maketrans('','',string.punctuation)
#    line=line.translate(puntable)
#    number=0
#    for word in line:
#        if word.isupper():
#            number+=1
#    line=line.upper()
#    uniqueletters=set(line)
#    uniqueletters.remove(' ')
#    return len(uniqueletters),number,uniqueletters

def myfunc(my_str):
    print(len(set(''.join([i.lower() for i in my_str if i.isalpha()]))))
    
phrase_one = "Well here we are"

phrase_two = "Back in sunny Xi'an!"

print(uniqueletter(phrase_one))
#print(uniqueletter(phrase_two))
myfunc(phrase_one)        
    

(6, 1, {'W', 'H', 'L', 'A', 'E', 'R'})
6


 ## Question Four: Counting lines (4 Points)
 
 Save the following Taylor Swift verse as a text file:

```python
taylorswift="I dont trust nobody\n
and nobody trusts me\n
Ill be the actress\n
starring in your bad dreams"
```

Then read it in, and count the number of lines programatically.

**Can you figure out how to do it as a one-liner?**

In [24]:
# Answer Four here
#taylorswift = '''I dont trust nobody\n
#and nobody trusts me\n
#Ill be the actress\n
#starring in your bad dreams'''
#
#with open('taylorswift.txt','w') as file:
#    file.write(taylorswift)
#with open('taylorswift.txt','r') as file:
#    lines = file.readlines()
#number_of_lines = len(lines)
#print(f'the verse has {number_of_lines} lines')
#print(taylorswift )
#print(len(file.read().splitlines()))
print(f'The verse has {sum(1 for line in open("taylorswift.txt") if line.strip())}')

The verse has 4


 ## Question Five: NumPy I

Create a 1D NumPy array with integers from 1 to 10. Then, perform the following tasks:

* Calculate the sum of all elements in the array.
* Find the mean value of the array.
* Multiply each element in the array by 2.
* Print the resulting array after the multiplication.

In [8]:
# Answer Five here
import numpy as np

array = np.arange(1,11)

array_sum = np.sum(array)

array_mean = np.mean(array)

array_multiplied = array * 2

print(array_sum)
print(array_mean)
print(array_multiplied)

55
5.5
[ 2  4  6  8 10 12 14 16 18 20]


## Question Six: NumPy II

Create a NumPy array of shape (3, 3) with random integers between 0 and 10. Then, perform the following tasks:

* Calculate the sum of all elements in the array.
* Find the maximum value in the array.
* Calculate the mean value of the array.
* Replace all even numbers in the array with -1.
* Print the resulting array after the replacement.

In [14]:
# Answer Six here
import numpy as np
arr2=np.random.randint(0,10,size=[3,3])
print(arr2)
print(arr2.sum())
print(arr2.max())
print(arr2.mean())
for i in range(arr2.shape[0]):
    for j in range(arr2.shape[1]):
        if arr2[i][j]%2==0:
            arr2[i][j]=-1
print(arr2)
            
        

[[6 5 8]
 [0 8 6]
 [8 4 9]]
54
9
6.0
[[-1  5 -1]
 [-1 -1 -1]
 [-1 -1  9]]
